project_id = "vxvcquifgwtbjghrcjbp"

[functions.create-incident]
verify_jwt = false

[functions.block-domain]
verify_jwt = true

[functions.approve-request]
verify_jwt = true

[functions.site-proxy]
verify_jwt = true

[functions.extension-config]
verify_jwt = true

[functions.extension-update-server]
verify_jwt = false